#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Installcode-server
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:30:00
#SBATCH --output=install-code-sevrer%A.out
#SBATCH --error=install-code-sevrer%A.err

set -e

module purge
module load 2022
module load Miniconda3/4.12.0
module load CUDA/11.7.0

source activate llamavid
conda install -c conda-forge code-server